#!/usr/bin/env python
# Generated by jaraco.develop 2.17.1
# https://pypi.python.org/pypi/jaraco.develop

import io
import sys

import setuptools

with io.open('README.txt', encoding='utf-8') as readme:
	long_description = readme.read()

needs_pytest = {'pytest', 'test'}.intersection(sys.argv)
pytest_runner = ['pytest_runner'] if needs_pytest else []
needs_sphinx = {'release', 'build_sphinx', 'upload_docs'}.intersection(sys.argv)
sphinx = ['sphinx'] if needs_sphinx else []

setup_params = dict(
	name='backports.unittest_mock',
	use_scm_version=True,
	author="Jason R. Coombs",
	author_email="jaraco@jaraco.com",
	description="backports.unittest_mock",
	long_description=long_description,
	url="https://bitbucket.org/jaraco/backports.unittest_mock",
	packages=setuptools.find_packages(),
	include_package_data=True,
	namespace_packages=['backports'],
	install_requires=[
	],
	setup_requires=[
		'setuptools_scm',
	] + pytest_runner + sphinx,
	tests_require=[
		'pytest',
	],
	extras_require={
		':python_version=="2.7"': [
			"mock",
		],
	},
	classifiers=[
		"Development Status :: 5 - Production/Stable",
		"Intended Audience :: Developers",
		"License :: OSI Approved :: MIT License",
		"Programming Language :: Python :: 2.7",
		"Programming Language :: Python :: 3.3",
		"Programming Language :: Python :: 3.4",
		"Programming Language :: Python :: 3.5",
	],
	entry_points={
		'pytest11': [
			"unittest_mock = backports.unittest_mock",
		],
	},
)
if __name__ == '__main__':
	setuptools.setup(**setup_params)
